### PR TITLE
Prevent NPE while logging errors

### LINKED ISSUE #260: Logging suppressed on errors and can we use the other jstl functions
Just started exploring the ACL tool locally, thank you the great work

Two things I needed some help with:
1.  **Seeing some log entries being suppressed( not reported), other than the NPE being reported - installing the ACL's via package - especially from the line below**

```
            installLog.addError(e.toString()); // ensure exception is added to installLog before it's persisted in log in finally clause
            throw e; // handling is different depending on JMX or install hook case
```
```
02.02.2018 19:58:06.670 *DEBUG* [qtp277129822-288-ACTool-Config-Worker] biz.netcentric.cq.tools.actool.configreader.YamlMacroChildNodeObjectsProviderImpl Loop for children of /content/www evaluates to 31 children
02.02.2018 20:01:36.963 *DEBUG* [qtp277129822-288-ACTool-Config-Worker] biz.netcentric.cq.tools.actool.history.impl.HistoryUtils create node: history_1517601696963_via_acltool-1.0
02.02.2018 20:01:36.984 *DEBUG* [qtp277129822-288-ACTool-Config-Worker] biz.netcentric.cq.tools.actool.history.impl.HistoryUtils delete obsolete history node: 
02.02.2018 20:01:36.985 *INFO* [qtp277129822-288-ACTool-Config-Worker] biz.netcentric.cq.tools.actool.history.impl.HistoryUtils Saved history in node: /var/statistics/achistory/history_1517601696963_via_acltool-1.0
02.02.2018 20:01:36.990 *DEBUG* [qtp277129822-288-ACTool-Config-Worker] biz.netcentric.cq.tools.actool.history.impl.AcHistoryServiceImpl Saved installed configuration files under : /var/statistics/achistory/history_1517601696963_via_acltool-1.0/installedConfigs
02.02.2018 20:01:37.123 *ERROR* [qtp277129822-288] biz.netcentric.cq.tools.actool.installhook.AcToolInstallHook Exception during execution of install hook: java.lang.NullPointerException
java.lang.NullPointerException: null
	at com.day.crx.packaging.impl.response.StreamedScriptResponse.onError(StreamedScriptResponse.java:131)
	at com.day.jcr.vault.fs.impl.JrVltProgressTrackerListener.onError(JrVltProgressTrackerListener.java:50)
	at biz.netcentric.cq.tools.actool.history.ProgressTrackerListenerInstallationLogger.addError(ProgressTrackerListenerInstallationLogger.java:29)
	at biz.netcentric.cq.tools.actool.impl.AcInstallationServiceImpl.installConfigurationFiles(AcInstallationServiceImpl.java:218)
	at biz.netcentric.cq.tools.actool.installhook.impl.AcToolInstallHookServiceImpl.installYamlFilesFromPackage(AcToolInstallHookServiceImpl.java:44)

```

**2. how can we use other functions like length etc. wanted to do something like this** 

`- IF ${lname.length == "5"}:`

### PR DESCRIPTION
**Pull request by kwin**
The ProgressTrackerListener doesn't support a null exception in its
onError message. Therefore remove all error messages not receiving a
throwable (or a null throwable).

This closes #260

### CODE REVIEW

File: accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/history/InstallationLogger.java [hunk 1]
```diff
@@ -11,10 +11,6 @@
 
     void addVerboseMessage(Logger log, String message);
 
-    void addError(final String error);
-
-    void addError(Logger log, String error);
```
Comment (ghenzler) [inline accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/history/InstallationLogger.java]: @kwin Shouldn't we leave that one in for consistency? It should log to log file and execution log (in the same way the other log severities allow for this)

File: accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/impl/AcInstallationServiceImpl.java [hunk 2]
```diff
@@ -214,8 +214,7 @@ public void installConfigurationFiles(PersistableInstallationLogger installLog,
             LOG.info("Successfully applied AC Tool configuration in " + msHumanReadable(executionTime));
             installLog.setExecutionTime(executionTime);
         } catch (Exception e) {
-            // TODO: separate exception
-            installLog.addError(e.toString()); // ensure exception is added to installLog before it's persisted in log in finally clause
+            installLog.addError("Could not process yaml files", e); // ensure exception is added to installLog before it's persisted in log in finally clause
```
Comment (ghenzler) [inline accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/impl/AcInstallationServiceImpl.java]: It would be good to pass in `LOG` here as well?

File: accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/history/InstallationLogger.java (hunk 1 above)
Comment (kwin) [reply accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/history/InstallationLogger.java]: This is used nowhere in the code!

File: accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/impl/AcInstallationServiceImpl.java (hunk 2 above)
Comment (kwin) [reply accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/impl/AcInstallationServiceImpl.java]: No need, as the exception is thrown in the next line anyways!
