### PR TITLE
Also interpret cost JSON object in case it is returned by oak search engine

### LINKED ISSUE #730: Invalid index detection in the cloud
For the automatic index detection from #714, it turns out that locally the cost is returned as 
`cost: { "s": 189540.0 }`
but in the cloud as 
` cost: { "s": { perEntry: 1.0, perExecution: 1.0, count: 47814 } }`
this seems to stem from https://github.com/apache/jackrabbit-oak/blob/5d10c51ff53dc05e2d36b2491689412ccd17b15d/oak-core/src/main/java/org/apache/jackrabbit/oak/query/ast/SelectorImpl.java#L448C34-L448C52

I'm not sure why the index is only a `AdvancedQueryIndex` in the cloud, to be checked.

The reason why the impl of #714 does not throw an exception is that https://www.javadoc.io/doc/com.fasterxml.jackson.core/jackson-databind/2.8.5/com/fasterxml/jackson/databind/JsonNode.html#asDouble(double) never throws an exception but always just returns the default if  a double cannot be coerced (even for a map instead of a skalar)

### PR DESCRIPTION
**Pull request by ghenzler**
Closes #730

### CODE REVIEW

File: accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/helper/QueryHelper.java [hunk 1]
```diff
@@ -143,14 +145,9 @@ static boolean hasQueryIndexForACLs(final Session session) throws RepositoryExce
         Row row = queryResult.getRows().nextRow();
         // inspired by https://github.com/apache/jackrabbit-oak/blob/cc8adb42d89bc4625138a62ab074e7794a4d39ab/oak-jcr/src/test/java/org/apache/jackrabbit/oak/jcr/query/QueryTest.java#L1092
         String plan = row.getValue("plan").getString();
-        String costJson = plan.substring(plan.lastIndexOf('{'));
-        
-        // use jackson for JSON parsing
-        ObjectMapper mapper = new ObjectMapper();
+        String costJsonStr = plan.substring(plan.lastIndexOf('{'));
```
Comment (kwin) [inline accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/helper/QueryHelper.java]: Probably we should log the JSON (on debug/verbose level) in case it changes in the future, so that we can more easily come up with a fix.

File: accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/helper/QueryHelper.java [hunk 2]
```diff
@@ -160,6 +157,18 @@ static boolean hasQueryIndexForACLs(final Session session) throws RepositoryExce
...
     }
 
+    static double getCostFromJsonStr(String jsonStr) throws JsonProcessingException, IOException {
+        // use jackson for JSON parsing
+        ObjectMapper mapper = new ObjectMapper().configure(JsonParser.Feature.ALLOW_UNQUOTED_FIELD_NAMES, true);
+
+        // read the json strings and convert it into JsonNode
+        JsonNode node = mapper.readTree(jsonStr);
+        
+        JsonNode sNode = node.get("s");
```
Comment (kwin) [inline accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/helper/QueryHelper.java:172]: We need some more null checks here and a unit test with invalid JSON.

File: accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/helper/QueryHelper.java [hunk 3]
```diff
@@ -160,6 +157,18 @@ static boolean hasQueryIndexForACLs(final Session session) throws RepositoryExce
...
+        double cost = sNode.isContainerNode() ? sNode.get("perExecution").asDouble(Double.MAX_VALUE) : sNode.asDouble(Double.MAX_VALUE);
```
Comment (kwin) [inline accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/helper/QueryHelper.java]: let us null check sNode.get("perExecution") as well.

**Review by kwin — CHANGES_REQUESTED** [review]

File: accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/helper/QueryHelper.java [hunk 4]
```diff
@@ -108,8 +114,8 @@ public static Set<String> getRepPolicyNodePaths(final Session session,
             boolean indexForRepACLExists = false;
             try {
                 indexForRepACLExists = hasQueryIndexForACLs(session);
-            } catch(IOException|RepositoryException e) {
-                LOG.warn("Cannot figure out if query index for rep:ACL nodes exist", e);
+            } catch(Exception e) {
+                LOG.warn("Could not detect if query index for rep:ACL nodes exists: {}", e.getMessage(), e);
             }
```
Comment (ghenzler) [inline accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/helper/QueryHelper.java:119]: no matter what exception is thrown this warning should be shown

File: accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/helper/QueryHelper.java [hunk 5]
```diff
@@ -137,20 +143,16 @@ public static Set<String> getRepPolicyNodePaths(final Session session,
...
         QueryResult queryResult = query.execute();
         Row row = queryResult.getRows().nextRow();
         // inspired by https://github.com/apache/jackrabbit-oak/blob/cc8adb42d89bc4625138a62ab074e7794a4d39ab/oak-jcr/src/test/java/org/apache/jackrabbit/oak/jcr/query/QueryTest.java#L1092
         String plan = row.getValue("plan").getString();
-        String costJson = plan.substring(plan.lastIndexOf('{'));
-        
-        // use jackson for JSON parsing
-        ObjectMapper mapper = new ObjectMapper();
+        LOG.debug("Execution plan and cost for {}: {}", EXPLAIN_QUERY_FOR_ACL_INDEX, plan);
+        String costJsonStr = StringUtils.substringAfter(plan, "cost:");
```
Comment (ghenzler) [inline accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/helper/QueryHelper.java:153]: just checking for `{` is also very unsafe - conceptually better to check for the string after `cost:`.  (`plan.substring(plan.lastIndexOf('{'))` returned only parts of the cost json)

**Review by kwin — APPROVED** [review]
Thanks for the fixes, looks good now.
