### PR TITLE
#503 Improve the performance of applying groups and users

### LINKED ISSUE #503: Improve the performance of applying groups and users (group_config / user_config)
If a setup has a large number of groups and users (in particular the number of users can be large like > 100,000), the execution time of the AC Tool can get fairly long. If the AC tool is triggered by the install hook that is included in a package, the installation using the package manager might run into a timeout:

```
[INFO] Package uploaded, now installing...
[INFO] ERROR: HTTP call to http://localhost:4503/crx/packmgr/service/console.html/etc/packages/amg/package-1.0.0-SNAPSHOT.zip?cmd=install&recursive=true failed: Read timed out (consider to increase the socket timeout using -Dvault.httpSocketTimeoutSec)
[INFO] ---------------
[INFO] HTTP call failed, try again (1/24) after 5 second(s)...
```

Increasing the timeout can solve the problem, but in some special cases that is not enough. 

One of the bottlenecks is `AuthorizableInstallerServiceImpl.getDeclaredMembersWithoutRegularUsers` which analyses each member of the group linearly. A solution with jdk8+ would be using a parallel stream to speed up this process, using jdk7, I believe we need to handle the threads manually.

### PR DESCRIPTION
**Pull request by ghenzler**
Closes #503

### CODE REVIEW

File: accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/authorizableinstaller/impl/PrefetchedAuthorizablesUserManager.java [hunk 1]
```diff
@@ -0,0 +1,125 @@
...
+
+    private final UserManager delegate;
+    private final Map<String, Authorizable> authorizableCache;
+
+    public PrefetchedAuthorizablesUserManager(UserManager delegate, InstallationLogger installLog) throws RepositoryException {
+        this.delegate = delegate;
+        this.authorizableCache = new HashMap<>();
+
+        long startPrefetch = System.currentTimeMillis();
+        Iterator<Authorizable> allAuthorizables = delegate.findAuthorizables(ALL_AUTHORIZABLES_QUERY);
```
Comment (ghenzler) [inline accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/authorizableinstaller/impl/PrefetchedAuthorizablesUserManager.java]: Prefetching all authorizables (using one query under the hood) turns out to be a lot more efficient than running many individual getAuthorizable() calls

Comment (kwin) [reply accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/authorizableinstaller/impl/PrefetchedAuthorizablesUserManager.java]: Do we know why? I once figured out in https://projects.netcentric.biz/wiki/display/CQ/Authorizable+vs.+Principal
> UserManager.getAuthorizable(String id)
This method is usually very fast because no query is involved because the node's jcr:uuid property (i.e. the nodes ID) is equal to UUID.nameUUIDFromBytes(name.getBytes(StandardCharsets.UTF_8)).
Therefore, Session.getNodeByIdentifier(...)is used to quickly retrieve the underlying node.
That is the case for all authorizables being created via the UserManager!

Is that observation no longer correct?

Comment (ghenzler) [reply accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/authorizableinstaller/impl/PrefetchedAuthorizablesUserManager.java]: So I just did measurements with a ~4000 authorizables setup and caching it like this brings down the installation time significantly. However I found that my current project's performance was improved but  @tomasalmeida 's problem  was not yet solved (~100.000 users in getDeclaredMembers()) - hence I followed this path further, see https://github.com/Netcentric/accesscontroltool/blob/1413e9315c2d3199e8f52dda087def95c39c3802/accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/authorizableinstaller/impl/PrefetchingUserManager.java#L40

Comment (tomasalmeida) [reply accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/authorizableinstaller/impl/PrefetchedAuthorizablesUserManager.java]: I deployed this code and tested it against an old version. Comparison values:

`time <deploy command>`

actool 2.3.2 
real	2m43.451s
real	2m45.496s
real	3m5.596s
real	2m57.520s

this branch (installed over the 2.3.2)
real	0m22.456s
real	0m18.718s
real	0m18.224s

I have in my local server more than 150000 users.

thank you so much for the implementation and the improvement 👏

File: accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/authorizableinstaller/impl/PrefetchingUserManager.java [hunk 2]
```diff
@@ -0,0 +1,196 @@
...
+
+    private final Map<String, Set<String>> nonRegularUserMembersByAuthorizableId = new HashMap<>();
+    private final Map<String, Set<String>> isMemberOfByAuthorizableId = new HashMap<>();
+
+    public PrefetchingUserManager(UserManager delegate, final ValueFactory valueFactory, InstallationLogger installLog)
+            throws RepositoryException {
+        this.delegate = delegate;
+
+        long startPrefetch = System.currentTimeMillis();
+        Iterator<Authorizable> allGroupsAndSystemUsersAndAnonymous = delegate.findAuthorizables(new Query() {
```
Comment (kwin) [inline accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/authorizableinstaller/impl/PrefetchingUserManager.java]: `authorizablesToPrefetch` instead of `allGroupsAndSystemUsersAndAnonymous`?

File: accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/authorizableinstaller/impl/PrefetchingUserManager.java [hunk 3]
```diff
@@ -0,0 +1,196 @@
...
+ * <p>
+ * The membership relationships are cached in lookup maps to quickly be able to query the repository state for both
+ * authorizable.declaredMemberOf() (this we call in this class also) and group.getDeclaredMembers(). Having called declaredMemberOf() for
+ * all groups of the repository has also retrieved all memberships (expect regular user memberships), hence the method getDeclaredMembers()
+ * does not have to be called anymore. This is particularly useful because that way the AC tool does not have to iterate over a potentially
+ * huge number of users in production to then only filter out a few relevant groups in the end (the AC Tool does not touch user memberships
+ * to groups).
+ * </p>
+ */
+class PrefetchingUserManager implements UserManager {
```
Comment (kwin) [inline accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/authorizableinstaller/impl/PrefetchingUserManager.java]: UserManager is a provider-type (https://github.com/apache/jackrabbit-oak/blob/trunk/oak-jackrabbit-api/src/main/java/org/apache/jackrabbit/api/security/user/UserManager.java), therefore this implementation is prone to break with future upgrades....

Since Jackrabbit/Oak doesn't provide a delegate class I would rather put this logic in a dedicated class which does not implement UserManager and only implement those methods which are actually called.

**Review by kwin — CHANGES_REQUESTED** [review]

File: accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/authorizableinstaller/impl/PrefetchingUserManager.java (hunk 3 above)
Comment (ghenzler) [reply accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/authorizableinstaller/impl/PrefetchingUserManager.java]: Fair enough, see https://github.com/Netcentric/accesscontroltool/blob/3b967710b9b09979b0c4bfdee41123f7175da0d0/accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/authorizableinstaller/impl/AuthInstallerUserManager.java#L13 to ensure new methods in UserManager will not break the AC tool in future

File: accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/authorizableinstaller/impl/PrefetchingUserManager.java (hunk 2 above)
Comment (ghenzler) [reply accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/authorizableinstaller/impl/PrefetchingUserManager.java]: done

**Review by kwin — APPROVED** [review]

**Review by tomasalmeida — APPROVED** [review]
