### PR TITLE
#538 Fail for yaml lists with more than one item underneath authorizable config

### LINKED ISSUE #538: Fail for yaml lists with more than one item underneath authorizable config
The following config should fail:
```
- group_config:

    - fragment-xyz-editor:
        - path: /home/groups/test
        # only one item allowed underneath group name, the hyphen is wrong here
        - isMemberOf:
            - fragment-xyz
```

### PR DESCRIPTION
**Pull request by ghenzler**
Closes #538

### CODE REVIEW

File: accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/configreader/YamlConfigReader.java [hunk 1]
```diff
@@ -217,18 +217,20 @@ private AuthorizablesConfig getAuthorizableBeans(
...
-                        final AuthorizableConfigBean tmpPrincipalConfigBean = getNewAuthorizableConfigBean();
-                        setupAuthorizableBean(tmpPrincipalConfigBean, currentPrincipalDataMap, currentAuthorizableIdFromYaml, isGroupSection);
-                        if (authorizableValidator != null) {
-                            authorizableValidator.validate(tmpPrincipalConfigBean);
-                        }
-                        authorizableBeans.add(tmpPrincipalConfigBean);
-                    } catch (AcConfigBeanValidationException e) {
-                        throw new AcConfigBeanValidationException("Invalid authorizable " + currentAuthorizableIdFromYaml, e);
+                
+                if(currentAuthorizableData.size() > 1) {
```
Comment (kwin) [inline accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/configreader/YamlConfigReader.java]: space missing

**Review by kwin — APPROVED** [review]
